languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
exclude_paths:
- "test.py"
engines:
  duplication:
    enabled: true
    condfig:
      languages:
        - python
    checks:
      Similar code:
        enabled: false
