#!/bin/ksh 
#
# An SMF method to start and stop the Diamond metric collector with
# custom SunOS (i.e. Solaris and Illumos) collectors.
#

BASE=/opt/local/diamond
CONF=/config/diamond/diamond.conf
PATH=/bin
PIDFILE=/tmp/diamond.pid

. /lib/svc/share/smf_include.sh

export PYTHONPATH=/opt/local/diamond/share/sunos-diamond-collectors/modules

start_service()
{
    print "Starting Diamond"
    print ${BASE}/bin/diamond -p $PIDFILE -c $CONF
    ${BASE}/bin/diamond -p $PIDFILE -c $CONF
}

stop_service()
{
    print "Stopping Diamond"

    ctid=$(svcprop -p restarter/contract $SMF_FMRI)

    test -f $PIDFILE && rm $PIDFILE

    for sig in 2 5 9
    do
	print "Signal is $sig"

        if pgrep -c $ctid 
	then
		print "kill contract $ctid with signal $sig"
		smf_kill_contract $ctid $sig 1 2
	else
		print "no processes with CTID $ctid"
	fi
    done
}

case $1 in
    start)  start_service
            ;;

    stop)   stop_service
            ;;

    restart)
            stop_service
            sleep 1
            start_service
            ;;

        *)  print "usage; ${0##*/} stop|start|restart"
            exit 1
esac
